[package]
name = "random"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "random"
path = "src/main.rs"

[dependencies]
hyper = { version = "^0.14", features = ["full"] }
tokio = { version = "^1", features = ["full"] }
tokio-util = "^0.6.8" 
pretty_env_logger = "0.4"
