version: "3.9"

services:
  web:
    ports:
      - 8010:3000
    environment:
      VIRTUAL_PORT: 8010
      VIRTUAL_HOST: random.cosi.clarkson.edu,random.cslabs.clarkson.edu,random
      LETSENCRYPT_HOST: random.cosi.clarkson.edu,random.cslabs.clarkson.edu
    build:
      context: .

networks:
  default:
    external:
      name: nginx-proxy
