version: "3.9"

services:
  web:
    ports:
      - 8004:8004
    environment:
      VIRTUAL_PORT: 8004
      VIRTUAL_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu,talks
      LETSENCRYPT_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu
    build:
      context: .

networks:
  default:
    external:
      name: nginx-proxy
